import LegalPage, { H } from "@/components/legal/LegalPage";
import { COMPANY } from "@/lib/legal";

export const dynamic = "force-dynamic";

export default function Terms() {
  return (
    <LegalPage title="Terms of Service">
      <p>These terms are between you and {COMPANY.name} (&quot;Vaulte&quot;, registered at {COMPANY.address}, registration {COMPANY.registration}) and govern your use of the Vaulte platform.</p>
      <H>1. What Vaulte is, and is not</H>
      <p>Vaulte is a technology platform that finds and instructs payment routes through independent, licensed third-party partners (banks, payment institutions, virtual-asset and foreign-exchange providers). <strong>Vaulte does not hold, receive on its own account, or custody your money or digital assets.</strong> Partners receive, convert and pay out funds under their own licences and terms, which you may be asked to accept. Vaulte is not a bank, a payment aggregator or a licensed money transmitter [CONFIRM WITH COUNSEL for each jurisdiction].</p>
      <H>2. Eligibility and verification</H>
      <p>You must complete identity or business verification (KYC/KYB) before live payments. We and our partners may ask for more information at any time, may limit or refuse any transaction, and may close an account where verification, sanctions or risk checks cannot be completed. Limits depend on your verification level.</p>
      <H>3. Quotes, fees and rates</H>
      <p>A quote shows the exchange rate, partner costs and Vaulte&apos;s markup and is firm until it expires. After you create a transfer from a quote, the quoted amount applies unless a partner fails and a replacement partner is used, in which case you still receive the quoted amount. Comparisons with bank wire costs are estimates. Fees are deducted from the amount sent.</p>
      <H>4. Permitted use</H>
      <p>You may use Vaulte only for lawful purposes you have truthfully declared (including purpose codes and invoices). You must not use it for sanctioned persons or jurisdictions, money laundering, terrorist financing, fraud, gambling, adult content, unregistered money services, or any activity prohibited in the country of the sender or the recipient. Transfers originating in India are fiat only. Personal remittances are subject to regulatory limits (including per-transaction, per-year and Liberalised Remittance Scheme limits) which we enforce.</p>
      <H>5. Holds, delays, reversals</H>
      <p>Transfers may be held for compliance review, rejected, or reversed through the partner. Timing shown is an estimate: banks and partners operate on their own cut-off times. If a payout fails, the partner refunds the sender according to its terms.</p>
      <H>6. Your responsibilities</H>
      <p>Keep credentials and API keys secret and enable two-factor authentication. You are responsible for the accuracy of recipient details and for the tax, customs, exchange-control and reporting obligations that apply to you. Vaulte does not give tax, legal or accounting advice. Documents generated by Vaulte (including payment advices) are records of Vaulte&apos;s systems and are not bank certificates (eFIRA, FIRC, eBRC).</p>
      <H>7. Liability</H>
      <p>[COUNSEL TO DRAFT: limitation and exclusion of liability, caps, indemnities, force majeure, and consumer-law carve-outs for each jurisdiction.]</p>
      <H>8. Changes, suspension, termination</H>
      <p>We may update these terms with notice. We may suspend or end access where required by law, a partner or a regulator, or for breach. You may close your account when no transfer is pending. Records are kept as the law requires.</p>
      <H>9. Governing law and disputes</H>
      <p>{COMPANY.governingLaw}. Complaints: see the <a className="text-gold underline" href="/legal/grievance">grievance officer page</a>.</p>
    </LegalPage>
  );
}
