import LegalPage, { H } from "@/components/legal/LegalPage";
import { COMPANY } from "@/lib/legal";

export const dynamic = "force-dynamic";

export default function Terms() {
  return (
    <LegalPage title="Terms of Service">
      <p>These terms are between you and {COMPANY.name} (&quot;Vaulte&quot;, registered at {COMPANY.address}, registration {COMPANY.registration}) and govern your use of the Vaulte platform, websites, APIs, invoices, payment links, checkout and milestone-deal tools. By creating an account, paying through a Vaulte link or accepting a Vaulte deal you agree to them together with our <a className="text-gold underline" href="/legal/privacy">Privacy Policy</a>, <a className="text-gold underline" href="/legal/aml">AML Policy</a>, <a className="text-gold underline" href="/legal/acceptable-use">Acceptable Use Policy</a> and <a className="text-gold underline" href="/legal/disclosures">Fee and Risk Disclosures</a>.</p>
      <H>1. What Vaulte is, and is not</H>
      <p>Vaulte is a technology platform that finds and instructs payment routes through independent, licensed third-party partners (banks, payment institutions, escrow agents, virtual-asset and foreign-exchange providers). <strong>Vaulte does not hold, receive on its own account, or custody your money or digital assets.</strong> Partners receive, convert, hold and pay out funds under their own licences and terms, which you may be asked to accept. Vaulte is not a bank, a payment aggregator, an escrow agent or a licensed money transmitter [CONFIRM WITH COUNSEL for each jurisdiction served]. Nothing here is investment, legal, tax or accounting advice.</p>
      <H>2. Eligibility and verification</H>
      <p>You must complete identity or business verification (KYC/KYB) before live payments. We and our partners may ask for more information at any time, may limit or refuse any transaction, and may close an account where verification, sanctions or risk checks cannot be completed. Limits depend on your verification level. We may check the identifiers you give us against official registers (for example VAT, company and tax registers and the LEI index) and will use the registered name and address to complete your profile; a difference from what you entered can send your application to manual review.</p>
      <H>3. Quotes, fees and rates</H>
      <p>A quote shows the exchange rate, partner costs and Vaulte&apos;s markup and is firm until it expires. After you create a transfer from a quote, the quoted amount applies unless a partner fails and a replacement partner is used, in which case you still receive the quoted amount. Comparisons with bank wire costs are estimates. Fees are deducted from the amount sent. See the <a className="text-gold underline" href="/legal/disclosures">Fee and Risk Disclosures</a>.</p>
      <H>4. Permitted use</H>
      <p>You may use Vaulte only for lawful purposes you have truthfully declared (including purpose codes and invoices) and only in line with the <a className="text-gold underline" href="/legal/acceptable-use">Acceptable Use Policy</a>. You must not use it for sanctioned persons or jurisdictions, money laundering, terrorist financing, fraud, unregistered money services, or any activity prohibited in the country of the sender or the recipient. Transfers originating in India are fiat only. Personal remittances are subject to regulatory limits (including per-transaction, per-year and Liberalised Remittance Scheme limits) which we enforce. Live payments are opened country by country; a country may be unavailable for live payments even if test mode works.</p>
      <H>5. Invoices, payment links and checkout (sellers)</H>
      <p>If you issue invoices, proforma invoices, payment links or checkout sessions you are the seller. You are responsible for their content, prices, tax particulars (rates, tax IDs, registration numbers) and for the goods or services you supply. Vaulte prints what you enter and does not check it for tax correctness. A proforma invoice is an estimate and not a tax invoice. Buyers pay through our licensed partners; Vaulte is not a party to your sale and does not guarantee that a buyer will pay. Refunds, returns and consumer rights as between you and your buyer are yours to handle. Return URLs you give us must be https and under your control.</p>
      <H>6. Milestone deals and escrow</H>
      <p>A deal lets a seller and a buyer agree milestones. In <strong>partner escrow</strong> a licensed escrow agent, not Vaulte, holds the buyer&apos;s money for each milestone and releases or returns it on the buyer&apos;s approval, on a deemed approval or on a dispute decision; the agent&apos;s own terms also apply. In <strong>pay-on-approval</strong> mode no one holds money before approval: Vaulte invoices the milestone when the buyer approves it (or at the start for milestones marked pay-upfront), and the seller bears the risk that a buyer does not pay. The buyer&apos;s approval window and the effect of silence are shown in the deal terms; silence for the stated number of days counts as approval. Anyone holding the buyer&apos;s deal link can act for the buyer, so the link must be kept private. Disputes are decided by Vaulte staff on the information provided by both parties as an operational decision about instructing the agent or the invoice; it is not arbitration or a court judgment and does not remove either party&apos;s legal rights [COUNSEL TO CONFIRM dispute process and any arbitration clause].</p>
      <H>7. Certificates and documents</H>
      <p>You can ask us to request an eFIRA, FIRC, eBRC, BRC or bank certificate for a completed transfer. Those documents are issued by banks, licensed partners or authorities, not by Vaulte; we pass your request on and attach what we receive, and cannot promise that an issuer will provide one or when. Documents generated by Vaulte (payment advices, statements, settlement reports, invoices) are records of Vaulte&apos;s systems and are not bank certificates.</p>
      <H>8. Holds, delays, reversals</H>
      <p>Transfers may be held for compliance review, rejected, or reversed through the partner. Timing shown is an estimate: banks and partners operate on their own cut-off times. If a payout fails, the partner refunds the sender according to its terms.</p>
      <H>9. Your responsibilities</H>
      <p>Keep credentials and API keys secret and enable two-factor authentication. You are responsible for the accuracy of recipient details and for the tax, customs, exchange-control and reporting obligations that apply to you. Keep your own copies of statements and certificates for the period the law requires.</p>
      <H>10. API and integrations</H>
      <p>API keys are credentials: you are responsible for activity under them. We may rate-limit or suspend keys that threaten the platform. Webhooks are delivered at least once and may repeat; verify signatures and handle duplicates. Third-party accounting or e-commerce connections you authorise are governed by those providers&apos; terms.</p>
      <H>11. Liability</H>
      <p>[COUNSEL TO DRAFT: limitation and exclusion of liability, caps, indemnities, force majeure, and consumer-law carve-outs for each jurisdiction.]</p>
      <H>12. Changes, suspension, termination</H>
      <p>We may update these terms with notice and ask you to accept the new version before you continue. We may suspend or end access where required by law, a partner or a regulator, or for breach. You may close your account when no transfer, milestone or dispute is pending. Records are kept as the law requires.</p>
      <H>13. Governing law and disputes</H>
      <p>{COMPANY.governingLaw}. Complaints: see the <a className="text-gold underline" href="/legal/grievance">grievance officer page</a>.</p>
    </LegalPage>
  );
}
