// PDF generation for payment advices and realisation packs (pdf-lib, no external services).
// Everything generated here is clearly labelled as a Vaulte record: it is NOT an eFIRA, FIRC, eBRC or bank certificate.
import { createHash } from "crypto";
import { PDFDocument, PDFFont, PDFPage, StandardFonts, rgb } from "pdf-lib";
import { db } from "@/lib/db";
import { loadDecrypted } from "@/lib/storage";
import { checklistFor, DOC_TYPES, type ChecklistItem } from "./types";

export const NOTICE = "This is a payment advice generated by Vaulte from its own records. It is NOT an eFIRA, FIRC, eBRC, bank realisation certificate or any certificate issued by a bank, authorised dealer, licensed partner or DGFT, and cannot substitute for one. Vaulte does not hold customer funds: the licensed partner received, converted and paid out the money.";

const clean = (s: unknown) => String(s ?? "").replace(/[^\x20-\x7E -ÿ]/g, "?");
const money = (minor: bigint, ccy: string) => { const dec = ["JPY", "KRW"].includes(ccy) ? 0 : 2; const n = Number(minor) / (dec ? 100 : 1); return `${ccy} ${n.toLocaleString("en-US", { minimumFractionDigits: dec, maximumFractionDigits: dec })}`; };
const fmtDate = (d?: Date | null) => (d ? d.toISOString().replace("T", " ").slice(0, 19) + " UTC" : "-");

class Writer {
  page!: PDFPage;
  y = 0;
  constructor(public pdf: PDFDocument, public font: PDFFont, public bold: PDFFont, private footer: string) { this.newPage(); }
  W = 595; H = 842; M = 48;
  newPage() {
    this.page = this.pdf.addPage([this.W, this.H]);
    this.y = this.H - this.M;
    this.page.drawText(clean(this.footer), { x: this.M, y: 24, size: 7, font: this.font, color: rgb(0.45, 0.45, 0.45) });
  }
  ensure(h: number) { if (this.y - h < this.M + 10) this.newPage(); }
  wrap(text: string, size: number, width: number, f = this.font): string[] {
    const out: string[] = [];
    for (const para of clean(text).split("\n")) {
      let line = "";
      for (const w of para.split(/\s+/)) {
        const t = line ? `${line} ${w}` : w;
        if (f.widthOfTextAtSize(t, size) > width && line) { out.push(line); line = w; } else line = t;
      }
      out.push(line);
    }
    return out;
  }
  h1(t: string) { this.ensure(34); this.page.drawText(clean(t), { x: this.M, y: this.y - 18, size: 18, font: this.bold }); this.y -= 34; }
  h2(t: string) { this.ensure(28); this.y -= 6; this.page.drawText(clean(t), { x: this.M, y: this.y - 12, size: 11, font: this.bold, color: rgb(0.1, 0.1, 0.15) }); this.page.drawLine({ start: { x: this.M, y: this.y - 16 }, end: { x: this.W - this.M, y: this.y - 16 }, thickness: 0.5, color: rgb(0.75, 0.75, 0.75) }); this.y -= 26; }
  p(t: string, size = 9, color = rgb(0.2, 0.2, 0.25)) { for (const l of this.wrap(t, size, this.W - 2 * this.M)) { this.ensure(size + 4); this.page.drawText(l, { x: this.M, y: this.y - size, size, font: this.font, color }); this.y -= size + 4; } this.y -= 2; }
  kv(rows: [string, string][]) {
    for (const [k, v] of rows) {
      const lines = this.wrap(v, 9, this.W - 2 * this.M - 150);
      this.ensure(lines.length * 13);
      this.page.drawText(clean(k), { x: this.M, y: this.y - 9, size: 8, font: this.font, color: rgb(0.45, 0.45, 0.5) });
      lines.forEach((l, i) => this.page.drawText(l, { x: this.M + 150, y: this.y - 9 - i * 12, size: 9, font: this.font }));
      this.y -= Math.max(14, lines.length * 12 + 2);
    }
    this.y -= 4;
  }
  table(head: string[], rows: string[][], widths: number[]) {
    const row = (cells: string[], f: PDFFont, size: number) => {
      const wrapped = cells.map((c, i) => this.wrap(c, size, widths[i] - 6, f));
      const h = Math.max(...wrapped.map(w => w.length)) * (size + 3) + 4;
      this.ensure(h);
      let x = this.M;
      wrapped.forEach((lines, i) => { lines.forEach((l, j) => this.page.drawText(l, { x: x + 2, y: this.y - size - j * (size + 3), size, font: f })); x += widths[i]; });
      this.y -= h;
    };
    row(head, this.bold, 7.5);
    this.page.drawLine({ start: { x: this.M, y: this.y + 1 }, end: { x: this.W - this.M, y: this.y + 1 }, thickness: 0.5, color: rgb(0.6, 0.6, 0.6) });
    for (const r of rows) row(r, this.font, 7.5);
    this.y -= 6;
  }
}

export interface PackData {
  generatedAt: string;
  transfer: { id: string; status: string; kind: string; createdAt: string; completedAt: string | null; originCountry: string; destCountry: string; sourceCurrency: string; destCurrency: string; sourceAmount: string; destAmount: string; sourceUsd: string; markupBps: number; markupUsd: string; partnerCostUsd: string; purposeCode: string | null; externalRef: string | null; efiraRef: string | null; route: { partners: string[]; legs: { partner: string; kind: string; rails: string[] }[]; token: string | null }; fx: unknown };
  sender: { name: string; country: string };
  recipient: { name: string; country: string };
  invoice: { number: string; currency: string; total: string } | null;
  organization: string;
  timeline: { at: string; event: string }[];
  ledger: { seq: number; at: string; kind: string; account: string; currency: string; amountMinor: string; usd: string }[];
  documents: { id: string; type: string; number: string | null; issuer: string | null; issuedOn: string | null; status: string; sha256: string | null; filename: string | null; source: string }[];
  checklist: ChecklistItem[];
}

export async function loadPackData(transferId: string, organizationId: string): Promise<PackData | null> {
  const t = await db.transfer.findFirst({ where: { id: transferId, organizationId }, include: { sender: true, recipient: true, organization: { select: { name: true } } } });
  if (!t) return null;
  const [invoice, docs, journals] = await Promise.all([
    t.invoiceId ? db.invoice.findUnique({ where: { id: t.invoiceId } }) : null,
    db.document.findMany({ where: { transferId, organizationId }, orderBy: { createdAt: "asc" } }),
    db.glJournal.findMany({ where: { transferId }, orderBy: { seq: "asc" }, include: { entries: { include: { account: true } } } }),
  ]);
  const route = t.route as unknown as PackData["transfer"]["route"] & { legs: PackData["transfer"]["route"]["legs"] };
  const funded = journals.find(j => j.kind === "MEMO_FUNDS_RECEIVED");
  const paid = journals.find(j => j.kind === "MEMO_PAYOUT");
  const timeline = [
    { at: t.createdAt.toISOString(), event: "Transfer created from a firm quote" },
    ...(funded ? [{ at: funded.createdAt.toISOString(), event: "Partner confirmed receipt of the sender's funds" }] : []),
    ...(paid ? [{ at: paid.createdAt.toISOString(), event: "Partner paid the recipient" }] : []),
    ...(t.completedAt ? [{ at: t.completedAt.toISOString(), event: "Transfer completed" }] : []),
  ];
  return {
    generatedAt: new Date().toISOString(),
    transfer: {
      id: t.id, status: t.status, kind: t.kind, createdAt: t.createdAt.toISOString(), completedAt: t.completedAt?.toISOString() ?? null, originCountry: t.originCountry, destCountry: t.destCountry,
      sourceCurrency: t.sourceCurrency, destCurrency: t.destCurrency, sourceAmount: t.sourceAmount.toString(), destAmount: t.destAmount.toString(), sourceUsd: t.sourceAmountUsd.toString(),
      markupBps: t.markupBps, markupUsd: t.markupUsd.toString(), partnerCostUsd: t.partnerCostUsd.toString(), purposeCode: t.purposeCode, externalRef: t.externalRef, efiraRef: t.efiraRef,
      route: { partners: route.partners, legs: route.legs.map(l => ({ partner: l.partner, kind: l.kind, rails: l.rails })), token: route.token }, fx: null,
    },
    sender: { name: t.sender.legalName, country: t.sender.country }, recipient: { name: t.recipient.legalName, country: t.recipient.country },
    invoice: invoice ? { number: invoice.number, currency: invoice.currency, total: String(invoice.totalAmount) } : null,
    organization: t.organization.name, timeline,
    ledger: journals.flatMap(j => j.entries.map(e => ({ seq: j.seq, at: j.entryDate.toISOString(), kind: j.kind, account: `${e.account.code} ${e.account.name}`, currency: e.currency, amountMinor: e.amountMinor.toString(), usd: e.baseUsdCents.toString() }))),
    documents: docs.map(d => ({ id: d.id, type: d.type, number: d.number, issuer: d.issuer, issuedOn: d.issuedOn?.toISOString() ?? null, status: d.status, sha256: d.sha256, filename: d.filename, source: d.source })),
    checklist: checklistFor({ destCountry: t.destCountry, originCountry: t.originCountry, kind: t.kind, status: t.status, purposeCode: t.purposeCode, invoiceId: t.invoiceId, efiraRef: t.efiraRef }, docs),
  };
}

/** Fingerprint over the facts (not the generation time) so a reader can tell whether a document was altered. */
export function fingerprint(d: PackData): string {
  const { generatedAt: _g, ...rest } = d;
  return createHash("sha256").update(JSON.stringify(rest)).digest("hex");
}

async function start(d: PackData, title: string) {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const fp = fingerprint(d);
  pdf.setTitle(title); pdf.setProducer("Vaulte"); pdf.setCreationDate(new Date(d.generatedAt));
  return { pdf, w: new Writer(pdf, font, bold, `${title} | transfer ${d.transfer.id} | generated ${d.generatedAt} | fingerprint ${fp.slice(0, 24)}`), fp };
}

function adviceBody(w: Writer, d: PackData, fp: string) {
  const t = d.transfer;
  w.kv([["Transfer reference", t.id], ["Status", t.status], ["Account holder", d.organization], ["Created", fmtDate(new Date(t.createdAt))], ["Completed", fmtDate(t.completedAt ? new Date(t.completedAt) : null)]]);
  w.h2("Parties");
  w.kv([["Sender", `${d.sender.name} (${d.sender.country})`], ["Recipient", `${d.recipient.name} (${d.recipient.country})`]]);
  w.h2("Amounts");
  const usd = (c: string) => `USD ${(Number(c) / 100).toLocaleString("en-US", { minimumFractionDigits: 2 })}`;
  w.kv([["Sent", money(BigInt(t.sourceAmount), t.sourceCurrency)], ["Recipient receives", money(BigInt(t.destAmount), t.destCurrency)], ["Value of amount sent", usd(t.sourceUsd)], ["Partner costs (spread + fees)", usd(t.partnerCostUsd)], ["Vaulte markup", `${usd(t.markupUsd)} (${t.markupBps} bps)`]]);
  w.h2("Route and references");
  w.kv([["Executed by", t.route.partners.join(", ")], ["Rails", Array.from(new Set(t.route.legs.flatMap(l => l.rails))).join(", ")], ["Stablecoin used", t.route.token ?? "None"], ["Partner payout reference", t.externalRef ?? "-"], ["Purpose code", t.purposeCode ?? "-"], ["Invoice", d.invoice ? d.invoice.number : "-"], ["eFIRA / remittance advice ref", t.efiraRef ?? "Not yet received from the partner"]]);
  w.h2("Notice");
  w.p(NOTICE, 8.5);
  w.p(`Data fingerprint (SHA-256): ${fp}`, 7, rgb(0.4, 0.4, 0.45));
}

export async function paymentAdvicePdf(d: PackData): Promise<Uint8Array> {
  const { pdf, w, fp } = await start(d, "Payment advice");
  w.h1("Payment advice");
  adviceBody(w, d, fp);
  return pdf.save();
}

/** Cover + advice + timeline + ledger extract + document checklist/index, followed by the attached PDFs and images. */
export async function realisationPackPdf(d: PackData): Promise<Uint8Array> {
  const { pdf, w, fp } = await start(d, "Realisation pack");
  w.h1("Realisation pack");
  w.p("Everything on file for this transfer, in one place, for your records, auditors and your bank. The documents issued by banks or DGFT are attached as received; Vaulte's own pages are labelled as such.", 9);
  adviceBody(w, d, fp);

  w.h2("Timeline");
  w.table(["When (UTC)", "Event"], d.timeline.map(e => [fmtDate(new Date(e.at)), e.event]), [150, 349]);

  w.h2("Document checklist");
  if (!d.checklist.length) w.p("No specific trade documents are expected for this transfer type.", 8.5);
  else w.table(["Document", "Status", "From", "Note"], d.checklist.map(c => [c.label, c.status.replace("_", " "), c.from, c.detail ?? ""]), [170, 70, 130, 129]);

  w.h2("Documents on file");
  if (!d.documents.length) w.p("None uploaded or received yet.", 8.5);
  else w.table(["Type", "Number", "Issuer", "Status", "SHA-256 (first 16)"], d.documents.map(x => [x.type, x.number ?? "-", x.issuer ?? "-", x.status, x.sha256 ? x.sha256.slice(0, 16) : "reference only"]), [70, 110, 130, 70, 119]);

  w.h2("Ledger extract (Vaulte's records)");
  w.p("Debits are positive, credits negative. Accounts 9100/9200 are memorandum records of customer money held by the licensed partner, not Vaulte's assets or liabilities.", 8);
  w.table(["#", "Journal", "Account", "Ccy", "Amount", "USD"], d.ledger.map(l => [String(l.seq), l.kind, l.account, l.currency, (Number(l.amountMinor) / 100).toFixed(2), (Number(l.usd) / 100).toFixed(2)]), [26, 105, 175, 32, 80, 81]);

  // Attachments (PDF pages are copied; images get a page of their own). Failures are listed, never fatal.
  const failures: string[] = [];
  for (const doc of d.documents) {
    if (!doc.filename || doc.status === "REJECTED") continue;
    const row = await db.document.findUnique({ where: { id: doc.id }, select: { storageKey: true, mime: true } });
    if (!row?.storageKey) continue;
    try {
      const data = await loadDecrypted(row.storageKey);
      const sep = pdf.addPage([w.W, w.H]);
      sep.drawText(clean(`Attachment: ${doc.type}${doc.number ? " " + doc.number : ""}`), { x: w.M, y: w.H - 120, size: 16, font: w.bold });
      sep.drawText(clean(`${doc.filename} | status ${doc.status} | SHA-256 ${doc.sha256 ?? "-"}`), { x: w.M, y: w.H - 145, size: 7.5, font: w.font });
      sep.drawText("The following pages are the document exactly as received (not altered by Vaulte).", { x: w.M, y: w.H - 165, size: 9, font: w.font });
      if (row.mime === "application/pdf") {
        const src = await PDFDocument.load(data, { ignoreEncryption: false });
        for (const pg of await pdf.copyPages(src, src.getPageIndices())) pdf.addPage(pg);
      } else {
        const img = row.mime === "image/png" ? await pdf.embedPng(data) : await pdf.embedJpg(data);
        const page = pdf.addPage([w.W, w.H]);
        const scale = Math.min((w.W - 2 * w.M) / img.width, (w.H - 2 * w.M) / img.height, 1);
        page.drawImage(img, { x: w.M, y: w.H - w.M - img.height * scale, width: img.width * scale, height: img.height * scale });
      }
    } catch (e) { failures.push(`${doc.type} ${doc.filename}: ${e instanceof Error ? e.message : "could not be merged"}`); }
  }
  if (failures.length) { w.newPage(); w.h2("Attachments that could not be merged"); w.p(failures.join("\n") + "\nDownload them individually from your account.", 8.5); }
  return pdf.save();
}
